import { Source } from '@/types/news';
import { v4 as uuidv4 } from 'uuid';

export const DEFAULT_SOURCES: Source[] = [
  {
    id: uuidv4(),
    name: 'OpenAI Blog',
    description: 'ChatGPT, GPT-4, DALL-E 등 OpenAI의 최신 AI 연구 및 제품 소식',
    rssUrl: 'https://openai.com/blog/rss.xml',
    websiteUrl: 'https://openai.com/blog',
    isActive: true,
  },
  {
    id: uuidv4(),
    name: 'Anthropic News',
    description: 'Claude AI를 만든 Anthropic의 AI 안전성 연구 및 기업 소식',
    websiteUrl: 'https://www.anthropic.com/news',
    isActive: true,
    scrapeConfig: {
      articleSelector: 'a[href*="/news/"]',
      titleSelector: 'h3, .title, span',
      linkSelector: 'a[href]',
      descriptionSelector: 'p',
    },
  },
  {
    id: uuidv4(),
    name: 'Google AI Blog',
    description: 'Gemini, Bard 등 Google의 AI 기술 개발 및 연구 동향',
    rssUrl: 'https://blog.google/technology/ai/rss/',
    websiteUrl: 'https://blog.google/technology/ai/',
    isActive: true,
  },
  {
    id: uuidv4(),
    name: 'Meta AI Blog',
    description: 'LLaMA, SAM 등 Meta의 오픈소스 AI 연구 및 메타버스 기술',
    websiteUrl: 'https://ai.meta.com/blog/',
    isActive: true,
    scrapeConfig: {
      articleSelector: 'article, .blog-post, a[href*="/blog/"]',
      titleSelector: 'h2, h3, .title',
      linkSelector: 'a[href]',
      descriptionSelector: 'p, .excerpt',
    },
  },
  {
    id: uuidv4(),
    name: 'Hugging Face Blog',
    description: '오픈소스 ML 커뮤니티의 최신 모델, 데이터셋, 라이브러리 소식',
    rssUrl: 'https://huggingface.co/blog/feed.xml',
    websiteUrl: 'https://huggingface.co/blog',
    isActive: true,
  },
  {
    id: uuidv4(),
    name: 'DeepMind Blog',
    description: 'AlphaFold, Gemini 등 Google DeepMind의 최첨단 AI 연구',
    rssUrl: 'https://deepmind.google/blog/rss.xml',
    websiteUrl: 'https://deepmind.google/discover/blog/',
    isActive: true,
  },
  {
    id: uuidv4(),
    name: 'NVIDIA AI Blog',
    description: 'AI 하드웨어 및 딥러닝 기술의 선두주자 NVIDIA 공식 블로그',
    rssUrl: 'https://blogs.nvidia.com/blog/category/deep-learning/feed/',
    websiteUrl: 'https://blogs.nvidia.com/blog/category/deep-learning/',
    isActive: true,
  },
  {
    id: uuidv4(),
    name: 'Microsoft AI Blog',
    description: 'Copilot, Azure AI 등 Microsoft의 AI 전략 및 제품 소식',
    rssUrl: 'https://blogs.microsoft.com/ai/feed/',
    websiteUrl: 'https://blogs.microsoft.com/ai/',
    isActive: true,
  },
  {
    id: uuidv4(),
    name: 'AWS Machine Learning Blog',
    description: 'Amazon의 클라우드 AI/ML 서비스 및 기술 튜토리얼',
    rssUrl: 'https://aws.amazon.com/blogs/machine-learning/feed/',
    websiteUrl: 'https://aws.amazon.com/blogs/machine-learning/',
    isActive: true,
  },
  {
    id: uuidv4(),
    name: 'MIT Technology Review AI',
    description: 'MIT가 발행하는 권위있는 AI 기술 및 산업 분석',
    rssUrl: 'https://www.technologyreview.com/topic/artificial-intelligence/feed/',
    websiteUrl: 'https://www.technologyreview.com/topic/artificial-intelligence/',
    isActive: true,
  },
  {
    id: uuidv4(),
    name: 'The Verge AI',
    description: 'AI 제품 리뷰, 뉴스 및 트렌드 분석',
    rssUrl: 'https://www.theverge.com/rss/ai-artificial-intelligence/index.xml',
    websiteUrl: 'https://www.theverge.com/ai-artificial-intelligence',
    isActive: true,
  },
  {
    id: uuidv4(),
    name: 'VentureBeat AI',
    description: 'AI 스타트업, 투자, 비즈니스 동향 전문 미디어',
    rssUrl: 'https://venturebeat.com/category/ai/feed/',
    websiteUrl: 'https://venturebeat.com/category/ai/',
    isActive: true,
  },
  {
    id: uuidv4(),
    name: 'The Decoder',
    description: 'AI 모델 출시, 연구 논문, 산업 뉴스 전문 매체',
    rssUrl: 'https://the-decoder.com/feed/',
    websiteUrl: 'https://the-decoder.com/',
    isActive: true,
  },
];

export const STORAGE_KEYS = {
  SOURCES: 'ai-news-sources',
  NEWS_ITEMS: 'ai-news-items',
  PROCESSED_NEWS: 'ai-news-processed',
  STYLE_TEMPLATES: 'ai-news-style-templates',
} as const;
